baseurl: /starter
permalink: pretty
future: true
markdown: kramdown
paginate: 5
repo: starter
github_org: maptime
maptime:
  chapter: Chapter name
  twitter: TwitterHandle
  #disqus: YOUR DISQUS USERNAME

gems:
  - jekyll-feed
